using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using UniversalTombLauncher.Extensions;

namespace UniversalTombLauncher.Utils
{
	/// <summary>
	/// Provides functionality to clean up and organize log files generated by the game.
	/// </summary>
	public static class LogCleaner
	{
		/// <summary>
		/// Name template for TRNG crash log files with a numbered identifier.
		/// </summary>
		private const string CrashLogFileNameTemplate = "Last_Crash_{0}.txt";

		/// <summary>
		/// Moves log files from the main game directory to a dedicated "logs" subdirectory.
		/// </summary>
		public static void TidyLogFiles(string gameDirectory)
		{
			string logsDirectory = Path.Combine(gameDirectory, "logs");

			if (!Directory.Exists(logsDirectory))
				Directory.CreateDirectory(logsDirectory);

			foreach (string file in Directory.GetFiles(gameDirectory))
			{
				string fileName = Path.GetFileName(file);

				if (IsValidLogFile(fileName))
				{
					string destPath = Path.Combine(logsDirectory, Path.GetFileName(file));
					MoveFileEx(file, destPath, true);
				}
				else if (IsValidNumberedCrashLog(fileName))
				{
					MoveNumberedLog(file, logsDirectory);
				}
			}

			bool isLogsDirEmpty = Directory.GetFileSystemEntries(logsDirectory).Length == 0;

			if (isLogsDirEmpty)
				Directory.Delete(logsDirectory);
		}

		/// <summary>
		/// Checks if the given file name matches known TRNG log file patterns.
		/// </summary>
		private static bool IsValidLogFile(string fileName)
			=> fileName.EqualsAny(StringComparison.OrdinalIgnoreCase,
				"db_patches_crash.bin", "DETECTED CRASH.txt", "LastExtraction.lst")
			|| fileName.EndsWith("_warm_up_log.txt", StringComparison.OrdinalIgnoreCase)
			|| Path.GetExtension(fileName).Equals(".log", StringComparison.OrdinalIgnoreCase);

		/// <summary>
		/// Checks if the given file name matches the numbered TRNG crash log pattern.
		/// </summary>
		private static bool IsValidNumberedCrashLog(string fileName)
			=> Regex.IsMatch(fileName, @"last_crash_\d+\.txt", RegexOptions.IgnoreCase);

		/// <summary>
		/// Moves a numbered crash log file to the logs directory, renaming it to avoid conflicts.
		/// </summary>
		private static void MoveNumberedLog(string logFile, string logsDirectory)
		{
			int logId = GetNextAvailableCrashLogId(logsDirectory);
			string normalizedLogId = logId.ToString().PadLeft(3, '0');

			string logFileName = string.Format(CrashLogFileNameTemplate, normalizedLogId);
			string destPath = Path.Combine(logsDirectory, logFileName);

			MoveFileEx(logFile, destPath, true);

			string memFilePath = Path.Combine(Path.GetDirectoryName(logFile), Path.GetFileNameWithoutExtension(logFile) + ".mem");

			if (File.Exists(memFilePath))
			{
				destPath = Path.Combine(logsDirectory, Path.GetFileNameWithoutExtension(logFileName) + ".mem");
				MoveFileEx(memFilePath, destPath, true);
			}
		}

		/// <summary>
		/// Finds the next available identifier for a new crash log file in the logs directory.
		/// </summary>
		private static int GetNextAvailableCrashLogId(string logsDirectory)
		{
			string[] existingLogFiles = Directory.GetFiles(logsDirectory, "last_crash_*.txt", SearchOption.TopDirectoryOnly);

			if (existingLogFiles.Length == 0)
				return 1;

			var takenNumbers = new List<int>();

			foreach (string logFile in existingLogFiles)
			{
				string fileName = Path.GetFileNameWithoutExtension(logFile);
				string logId = fileName.Split('_').Last();

				if (int.TryParse(logId, out int id))
					takenNumbers.Add(id);
			}

			return takenNumbers.Max() + 1;
		}

		/// <summary>
		/// Moves a file from source to destination, optionally overwriting existing files.
		/// </summary>
		private static void MoveFileEx(string source, string dest, bool overwrite = false)
		{
			File.Copy(source, dest, overwrite);
			File.Delete(source);
		}
	}
}
